### PR TITLE
Add OLAS token

### PR DESCRIPTION
**Pull request by kupermind**
Add OLAS token request, reference to #454

### CODE REVIEW

**Review by Groovytent — CHANGES_REQUESTED** [review]
Please add your socials and token details on polygonscan, also please share the logo in svg format to proceed with approvals.

**Comment by kupermind** [comment]
@Groovytent I am not sure how we can update the token info on polygonscan, as it is owned by the mapper deployer. Please provide some references on how we could act further.

**Comment by mayanks1211** [comment]
@kupermind In that case, please add the token logo in the SVG format, and about the socials, you can do that later by contacting the Etherscan team.

**Comment by kupermind** [comment]
Had to close this one in order to resolve conflicts correctly.

**Pull request closed without merging**
