### PR TITLE
Add swappable tag to Cipher

### PR DESCRIPTION
**Pull request by cphertech**
Added tag swappable on cipher token

### CODE REVIEW

**Comment by cphertech** [comment]
Dear Team, 
Please review the PR #333 
Thank you

**Review by Groovytent — COMMENTED** [review]
Please follow this document in order to add your token: https://github.com/maticnetwork/polygon-token-list#adding-or-updating-a-token
Kindly only make necessary changes.

**Comment by cphertech** [comment]
Hello Team,
Please review and approve PR #353.
https://github.com/maticnetwork/polygon-token-list/pull/353
Thank you.
Best regards,
Cipher Team.

**Comment by cphertech** [comment]
Hello Team,
Please review and approve PR #353.
https://github.com/maticnetwork/polygon-token-list/pull/353
Thank you.
Best regards,
Cipher Team.

**Pull request closed without merging**
