### PR TITLE
Add {VERSE}: {Verse} Bitcoin.com Token

### PR DESCRIPTION
**Pull request by vm06007**
This closes https://github.com/maticnetwork/polygon-token-list/issues/418

### CODE REVIEW

**Comment by vm06007** [comment]
@Groovytent could you take a look please?

**Review by mayanks1211 — CHANGES_REQUESTED** [review]
You've added both 'pos' and 'fx' tags. Make sure to add only one 'bridge' tag.
If you do not want to make the token bridgable please add the 'noDeposit' and 'noWithdraw' tags.

**Comment by vm06007** [comment]
> You've added both 'pos' and 'fx' tags. Make sure to add only one 'bridge' tag. If you do not want to make the token bridgable please add the 'noDeposit' and 'noWithdraw' tags.

addressed here: https://github.com/maticnetwork/polygon-token-list/pull/426/commits/2723e1ebf5d560d8faedb003de9db1eba5d648b2

**Review by Groovytent — APPROVED** [review]
LGTM

**Review by mayanks1211 — APPROVED** [review]
LGTM

**Comment by DONOVA28** [comment]
👍

**Comment by vm06007** [comment]
@Groovytent @DONOVA28 @mayanks1211 thanks for merging this, but we've noticed the metadata still is wrong on the contract, who can assist to correct this?

https://polygonscan.com/token/0xc708d6f2153933daa50b2d0758955be0a93a8fec#readContract#F7 we would like this to say `VERSE` not `fxVERSE` 

https://polygonscan.com/token/0xc708d6f2153933daa50b2d0758955be0a93a8fec#readContract

**Pull request merged**
