### PR TITLE
Add tag Swapable on CIPHER (CPR)

### PR DESCRIPTION
**Pull request by cphertech**
Added "Swapable" tag on cipher token

### CODE REVIEW

**Review by py-zoid — CHANGES_REQUESTED** [review]
Fix formatting errors. Perform the third step from the [readme file on adding a token](https://github.com/maticnetwork/polygon-token-list#adding-or-updating-a-token).

**Comment by cphertech** [comment]
Fixed formatting errors.Please check it and do the needful

**Comment by py-zoid** [comment]
Pushed the changes with PR #380 .

**Comment by cphertech** [comment]
Dear Team,
Good evening. Thank you so much for updates. We appreciate your support and
service.
Best Regards
Cipher Team.

**Comment by cphertech** [comment]
Dear Team,
Good evening. Thank you so much for updates. We appreciate your best
support and service.
Best Regards
Cipher Team.

**Pull request closed without merging**
