### PR TITLE
adding kocaki token

### PR DESCRIPTION
**Pull request by BM1KE**

### CODE REVIEW

**Comment by py-zoid** [comment]
Please raise an issue [here](https://github.com/maticnetwork/polygon-token-list/issues/new?assignees=&labels=add+token+request&template=add_token_request.md&title=Add+%7BTOKEN_SYMBOL%7D%3A+%7BTOKEN_NAME%7D) to get your token added to the list.

**Comment by BM1KE** [comment]
I did that first. Its says not mapped
https://github.com/maticnetwork/polygon-token-list/issues/176


Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by appumenon** [comment]
Hey @BM1KE 
We only show mapped tokens on the Polygon wallet currently.  Do go through the below docs for mapping related help.
https://docs.polygon.technology/docs/develop/ethereum-polygon/submit-mapping-request/

**Comment by BM1KE** [comment]
Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Pull request closed without merging**
